/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class keystoneml_utils_external_EncEval */

#ifndef _Included_keystoneml_utils_external_EncEval
#define _Included_keystoneml_utils_external_EncEval
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     keystoneml_utils_external_EncEval
 * Method:    computeGMM
 * Signature: (II[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_keystoneml_utils_external_EncEval_computeGMM
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     keystoneml_utils_external_EncEval
 * Method:    calcAndGetFVs
 * Signature: ([FII[F[F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_keystoneml_utils_external_EncEval_calcAndGetFVs
  (JNIEnv *, jobject, jfloatArray, jint, jint, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
