/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_external_ImageFeatures */

#ifndef _Included_utils_external_ImageFeatures
#define _Included_utils_external_ImageFeatures
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_external_ImageFeatures
 * Method:    getSIFTs
 * Signature: (IIIII[F)[S
 */
JNIEXPORT jshortArray JNICALL Java_utils_external_ImageFeatures_getSIFTs
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jfloatArray);

/*
 * Class:     utils_external_ImageFeatures
 * Method:    computeGMM
 * Signature: (II[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_utils_external_ImageFeatures_computeGMM
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     utils_external_ImageFeatures
 * Method:    calcAndGetFVs
 * Signature: ([FII[F[F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_utils_external_ImageFeatures_calcAndGetFVs
  (JNIEnv *, jobject, jfloatArray, jint, jint, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
