/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class extLibrary_SIFTExtractor */

#ifndef _Included_extLibrary_SIFTExtractor
#define _Included_extLibrary_SIFTExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     extLibrary_SIFTExtractor
 * Method:    getSIFTs
 * Signature: (IIIII[F)[S
 */
JNIEXPORT jshortArray JNICALL Java_extLibrary_SIFTExtractor_getSIFTs
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jfloatArray);

/*
 * Class:     extLibrary_SIFTExtractor
 * Method:    calcAndGetFVs
 * Signature: ([FII[F[F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_extLibrary_SIFTExtractor_calcAndGetFVs
  (JNIEnv *, jobject, jfloatArray, jint, jint, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     extLibrary_SIFTExtractor
 * Method:    computeGMM
 * Signature: (II[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_extLibrary_SIFTExtractor_computeGMM
  (JNIEnv *, jobject, jint, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
